### PR TITLE
Fix pagination

### LINKED ISSUE #132: `pagination` object doesn't always contain `cursor`
https://github.com/DaCasBe/TwitchPy/blob/dd5f1902b8f6de11b8c583fd10e41d99728aef12/twitchpy/_utils/http.py#L63

https://dev.twitch.tv/docs/api/reference/#get-streams

If you search for a list of objects that doesn't have more than one page, the linked line causes the library to fail. As shown in the documentation, the `pagination` object can exist without having the `cursor` object inside of it.

I can try to make a PR for this soon-ish, but figured I'd submit a bug to make sure it's visible.

This can be easily repro'd by doing running `twitch.get_streams(first=1, user_id='<any user not online>')`

### PR DESCRIPTION
**Pull request by ImDevinC**
Fixes #132

### CODE REVIEW

**Comment by ImDevinC** [comment]
@DaCasBe any chance I can get this reviewed? Would be great to get this into the pypi distribution. Thanks!

**Comment by DaCasBe** [comment]
I'm sorry I haven't seen this before. I'll check it ASAP.

**Comment by ImDevinC** [comment]
@DaCasBe anything I can do to help get this approved? Thanks!

**Comment by DaCasBe** [comment]
Sorry, I've not been at home till today. I'm going to review it right now, but firstly, please change the branch's name to a reference to the issue.

**Comment by ImDevinC** [comment]
Thanks @DaCasBe, here's the new PR since the branch has changed: https://github.com/DaCasBe/TwitchPy/pull/133

**Pull request closed without merging**
